# ============================================================
# CONFIGURACION BASE DE DATOS - PostgreSQL
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/pagos_distribuidos
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / HIBERNATE
# ============================================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# SERVIDOR
# ============================================================
server.port=8084
spring.application.name=plataformaok
spring.jackson.default-property-inclusion=non_null
